name: Ejercicio 2 - Workflow con checkout

on:
  push:

jobs:
  comprobar-repositorio:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Mostrar contenido del repositorio
        run: ls -la

      - name: Mostrar contenido del README
        run: cat README.md
